Repository FalkorDB/docs, pull requests merged in 2025-02, with the labels that each got.

#122 Update kafka-connect.md
  integration/kafka-connect.md
Labels: Review effort [1-5]: 1

#121 add kafka connect sink doc
  .wordlist.txt
  integration/index.md
  integration/kafka-connect.md
Labels: Review effort [1-5]: 2

#124 update text indexing/search on edges
  cypher/indexing.md
Labels: Review effort [1-5]: 1

#133 Update index.md
  .wordlist.txt
  index.md
  integration/kafka-connect.md
  integration/rest.md
Labels: Review effort 1/5
